{% set version = "3.4.0" %}


package:
  name: oq-engine
  version: {{ version }}

source:
  url: https://github.com/gem/oq-engine/archive/v{{ version }}.tar.gz
  sha256: 1a334d280caea37d9d6a5a38ee9cb410b1067fd9714d7d4ef3894223bb6ddaf5

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - h5py >=2.9,<2.10
    - numpy >=1.16,<1.17
    - scipy >=1.3,<1.4
    - pyzmq <18.2
    - psutil >=2.0,<5.7
    - shapely >=1.3,<1.7
    - docutils >=0.11,<0.15
    - decorator >=4.3
    - django >=1.11,<2.3
    - matplotlib-base >=2,<3.2
    - requests >=2.20,<2.23
    - pyshp
    - pyyaml
    - toml
    - rtree
    
test:
  imports:
    - openquake.hazardlib

about:
  home: https://github.com/gem/oq-engine
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'The OpenQuake Engine is an open source application that allows users to compute seismic hazard and seismic risk of earthquakes on a global scale'
  description: |
    The OpenQuake Engine is an open source application that allows users to compute seismic hazard and seismic risk of earthquakes on a global scale. It runs on Linux, macOS and Windows, on laptops, workstations, standalone servers and multi-node clusters.
  doc_url: https://github.com/gem/oq-engine/tree/engine-2.5#openquake-engine
  dev_url: https://github.com/gem/oq-engine

extra:
  recipe-maintainers:
    - mhearne-usgs
