travis:
  secure:
    BINSTAR_TOKEN: i2H7s+0Pjafn5V2HCYOMhxCFEse8KhL3xdKSTNmunmRwXEXo2ANzigY+5YsCpQckCn/5YcO4qU+rmKD5Ql6laksFQRssZMQjTkjVTutq5Px4MtteaZfOW5q4rFU3kaFSuHNygICE4WzDAA6MYc/no6BaGjJZRbxBomnuYSE1rXLPV1bDZ58UqmnTJM3t9L7zj3xBJB1oaHPUrre99dz/btgISklHGFQVZBdB7+aU5a4aLdPrlZNi6kQOVStiTe/qRuTiWkKOXiXnZvarspWBWO5ive08m2pqCerOPdzl75E8L5XUo0RmeFzr2telJvvIOzyaEFrFGT07dadFldpwL1jcKEL//r40/uyqQNEN85+kmJM5hQ0qaGUSGMGkqYnqVzwcOUMEada20wyecLJKJpG/TEnl9m+X00GuA58VrEVQJ3cfqg7l1HIdN7358seu9dcGM88PK2Ukpi500Vsq5bCInwVjowmD8aM1vm5/s/ay8nDJ1fU1hzqOJbYk6SjsbnD48Aop/EijHuOdxbqrvGmzWtPSp4V4u7ndDxSHC2pSu9rUFIf4nDhY/zFZui30PnsvOktiaDwrDbgkYafSK3RJu5oD+Flq80FnmiON+wkwOua/6Z+qgNafMcG1GiWdCV7cxu7/lCUuORSyDyz+CPDl3nOF7RYywhiEiLNoPGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
